### ISSUE TITLE
Translation button is not working properly 

### ISSUE THREAD

**Issue by XAMIR555** [sds100/KeyMapper#189] opened 2019-05-25 11:43 UTC
#### Project Information

* Repository---------------:[Here](https://github.com/sds100/KeyMapper)
* Project Name------------: [KeyMapper](https://github.com/sds100/KeyMapper/releases)
* Publisher----------------: [sds100](https://github.com/sds100)
* My GitHub account------:[Here](https://github.com/XAMIR555)

#### Expected behavior

When I click the Translation button, the translation of different languages should be displayed

#### Actual behavior

Translation button is not working properly 

#### How to reproduce
* Open the [application](https://github.com/sds100/KeyMapper/releases)
* Click the 3 horizontal line at the bottom left
* click on about
* click on translate  option
* Note the Bug

* Browser/App version-: 1.1.0 Beta 6 
* Operating system----: 9.0.0

#### Recording Of The Bug
![20190525_160944](https://user-images.githubusercontent.com/49812927/58368738-0bd9ba00-7ea6-11e9-83f4-75fe97bcb5ea.gif)

**Comment by sds100** [comment] 2019-05-26 10:20
I am aware of the problem. The

**Comment by sds100** [comment] 2019-05-26 10:29
The problem is displaying the code snippets

**Comment by sds100** [comment] 2019-05-26 11:19
Fixed. Will take a while for github to sync the changes to the wiki page on the server so may not see it fixed instantly.

**Closed by sds100** 2019-05-26 11:19 UTC
Labels: bug
